"""
simulate/partition_data.py
--------------------------
Partition the combined client data into N equal-sized splits for simulation.

Usage:
    python simulate/partition_data.py --num-clients 10

Creates:
    data/sim_client_{1..N}_train.csv
    data/sim_client_{1..N}_test.csv
"""
from __future__ import annotations

import argparse
import os
import sys

import numpy as np
import pandas as pd


def _load_all(base_dirs: list[str], split: str) -> pd.DataFrame:
    """Concatenate all existing client CSVs for the given split (train/test)."""
    frames = []
    for root in base_dirs:
        pattern = f"client_{{i}}_{split}.csv"
        for filename in sorted(os.listdir(root)):
            if filename.endswith(f"_{split}.csv") and filename.startswith("client_"):
                path = os.path.join(root, filename)
                frames.append(pd.read_csv(path))
    if not frames:
        print(f"[ERROR] No *_{split}.csv files found in {base_dirs}")
        sys.exit(1)
    combined = pd.concat(frames, ignore_index=True)
    print(f"[PARTITION] Loaded {len(combined):,} {split} rows from {len(frames)} files.")
    return combined


def partition_and_save(
    data_dir: str,
    num_clients: int,
    prefix: str = "sim_client",
    seed: int = 42,
) -> list[tuple[str, str]]:
    """
    Partition combined data into num_clients equal splits.
    Returns a list of (train_path, test_path) tuples.
    """
    train_df = _load_all([data_dir], "train")
    test_df  = _load_all([data_dir], "test")

    # Shuffle before splitting so each partition is representative
    rng = np.random.default_rng(seed)
    train_df = train_df.sample(frac=1, random_state=rng.integers(0, 2**31)).reset_index(drop=True)
    test_df  = test_df.sample(frac=1, random_state=rng.integers(0, 2**31)).reset_index(drop=True)

    train_splits = np.array_split(train_df, num_clients)
    test_splits  = np.array_split(test_df,  num_clients)

    paths = []
    for i, (tr, te) in enumerate(zip(train_splits, test_splits), start=1):
        train_path = os.path.join(data_dir, f"{prefix}_{i}_train.csv")
        test_path  = os.path.join(data_dir, f"{prefix}_{i}_test.csv")
        tr.to_csv(train_path, index=False)
        te.to_csv(test_path,  index=False)
        print(
            f"[PARTITION] Client {i:>2}: "
            f"{len(tr):>6} train rows → {train_path}  |  "
            f"{len(te):>5} test rows → {test_path}"
        )
        paths.append((train_path, test_path))

    return paths


def build_env_block(paths: list[tuple[str, str]], prefix: str = "sim_client") -> str:
    """Return the .env variable block for the simulation clients."""
    lines = ["# Simulation client datasets (auto-generated by partition_data.py)"]
    for i, (tr, te) in enumerate(paths, start=1):
        lines.append(f"CLIENT_{i}_TRAINING_SET={tr}")
        lines.append(f"CLIENT_{i}_TESTING_SET={te}")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Partition existing client data into N splits for simulation."
    )
    parser.add_argument("--num-clients", "-n", type=int, default=10,
                        help="Number of client partitions to create (default: 10).")
    parser.add_argument("--data-dir", default="./data",
                        help="Directory containing original client CSVs (default: ./data).")
    parser.add_argument("--prefix", default="sim_client",
                        help="Filename prefix for generated files (default: sim_client).")
    parser.add_argument("--seed", type=int, default=42,
                        help="Random seed for shuffling (default: 42).")
    parser.add_argument("--print-env", action="store_true",
                        help="Print the .env variable block to stdout after partitioning.")
    args = parser.parse_args()

    paths = partition_and_save(
        data_dir=args.data_dir,
        num_clients=args.num_clients,
        prefix=args.prefix,
        seed=args.seed,
    )

    print(f"\n[PARTITION] Done. {args.num_clients} client partitions created in {args.data_dir}/")

    if args.print_env:
        print("\n# ── Paste into your .env ──────────────────────────────────────────")
        print(build_env_block(paths, prefix=args.prefix))


if __name__ == "__main__":
    main()
